### PR TITLE
Use i18n Keys

### PR DESCRIPTION
**Pull request by Vaishakh-SM**
**End-user friendly description of the problem this fixes or functionality that this introduces**

Right now, several instances of plain English language are used in the codebase. Using i18 keys would ensure better inclusivity by enabling users to use different languages.

---
**Link of any specific issues this addresses**

[Issue#4280](https://github.com/All-Hands-AI/OpenHands/issues/4280)

### CODE REVIEW

**Comment by Vaishakh-SM** [comment]
@amanape , as mentioned [here](https://github.com/All-Hands-AI/OpenHands/pull/4397#issuecomment-2501678978), the tests are failing since I've changed hard-coded alt-text values. Shall I update this in this PR?

**Comment by amanape** [comment]
Feel free to do so. I think I'll be able to resolve the conflicts myself later this week (apparently I should be able to resolve them 😅)

**Comment by neubig** [comment]
@amanape , I think OpenHands was able to clean this up, please TAL!

**Comment by mamoodi** [comment]
@amanape any chance you have a few minutes to review this PR please?

**Review by amanape — APPROVED** [review]
Sorry for the delay, LGTM!

**Comment by mamoodi** [comment]
@Vaishakh-SM just needs a final conflict resolution for merge if you have a few minutes 🙏

**Pull request merged**
