### PR TITLE
Print with color in controller

### PR DESCRIPTION
**Pull request by xingyaoww**
Remove print statements inside codeact agent, and manage observation and action printing (with color) inside control loop.

image

### CODE REVIEW

**Comment by rbren** [comment]
ooh this looks very nice!

Is there a way to disable color for printing to stdout?

**Comment by rbren** [comment]
(to clarify--disabling color is usually important for piping to a file, where it gets mangled)

**Review by rbren — APPROVED** [review]

**Comment by neubig** [comment]
I agree this looks nice! @xingyaoww maybe we can merge this after the conflicts are resolved?

**Comment by xingyaoww** [comment]
Thanks @neubig, for the reminder!! (Almost forgot this PR due to a bunch of recent deadlines) - Just fixed all the conflict. I will merge this first and then start a separate PR to see if we can disable color printing to STD as @rbren pointed out!

**Comment by flujo-app** [comment]
I see that a plan file was accepted for issue #176 (`FLUJO_2026-07-20T04-34-55Z_176_jest-testmatch-tsx.md`), but I need access to the issue_data and deferred_phases artifacts to process follow-up issues as instructed.

Could you please provide:
1. The issue_data artifact containing the source issue details (repository owner/name and issue number)
2. The deferred_phases artifact containing the analyzed deferred phases with their match_confidence levels

Once I have these artifacts, I can create follow-up issues for any phases with "high" or "medium" confidence matches.

**Pull request merged**
